### ISSUE TITLE
Fatal error during activating

### ISSUE THREAD

**Issue by ZsomborA** [ciknowles/mqtt-cogs#19]
Hi there! First of all, a huge thank you for developing this plugin for WordPress. Could you help me understand why I’m getting a fatal error message when trying to activate the plugin during installation? 

[19-Apr-2024 11:00:21 UTC] PHP Deprecated: version_compare(): Passing null to parameter #2 ($version2) of type string is deprecated in /home/tesztfor/bayersec.hu/wp-content/plugins/mqtt-cogs-master/mqtt-cogs.php on line 51 [19-Apr-2024 11:00:21 UTC] PHP Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given in /home/tesztfor/bayersec.hu/wp-content/plugins/mqtt-cogs-master/MqttCogs_Plugin.php:95 Stack trace: #0 /home/tesztfor/bayersec.hu/wp-content/plugins/mqtt-cogs-master/MqttCogs_LifeCycle.php(29): MqttCogs_Plugin->initOptions() #1 /home/tesztfor/bayersec.hu/wp-content/plugins/mqtt-cogs-master/mqtt-cogs_init.php(34): MqttCogs_LifeCycle->install() #2 /home/tesztfor/bayersec.hu/wp-content/plugins/mqtt-cogs-master/mqtt-cogs.php(100): MqttCogs_init() #3 /home/tesztfor/bayersec.hu/wp-admin/includes/plugin.php(2389): include_once(‘/home/tesztfor/…’) #4 /home/tesztfor/bayersec.hu/wp-admin/includes/plugin.php(675): plugin_sandbox_scrape() #5 /home/tesztfor/bayersec.hu/wp-admin/plugins.php(60): activate_plugin() #6 {main} thrown in /home/tesztfor/bayersec.hu/wp-content/plugins/mqtt-cogs-master/MqttCogs_Plugin.php on line 95

**Comment by ZsomborA** [comment]
Which PHP version should I use?
